
services:
  frontend: 
    image: taski-front-multi:latest
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taski-front
    restart: always
    depends_on:
      - backend
    ports: 
      - '80:80'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 30s
  backend:
    image: taski-back-multi:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taski-back
    command: sh -c "python manage.py runserver 0.0.0.0:8000 && python manage.py migrate"
    restart: always
    ports: 
    - "8000:8000"
    volumes:
        - ./backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 30s