apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: maxtever/taski-back-multi:latest
          # imagePullPolicy: Never
          ports:
            - containerPort: 8000
          command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
      volumes:
        - name: backend-data
          persistentVolumeClaim:
            claimName: backend-pvc